### ISSUE TITLE
Sync does not start because not enough space

### ISSUE THREAD

**Issue by beankylla** [Infomaniak/desktop-kDrive#126]
*Note: Please write your issue only in english*

**Description**
Kdrive on linux. My sync would not start and stay blocked on step 1. I deleted the config folder to start with a clean slate. So i had most files on both my computer AND Kdrive. My computer had ~500 GB free space available. I wanted to sync my files (mostly the delta since it had not synced so ~50 gigs top) and all files are already on my comp, i mostly need to upload the new ones to kdrive. Kdrive tests remaining disk spaces and assesses that there is not enough space on disk without considering the files from Kdrives that are already present on the disk

**Steps to reproduce**
1. Sync a comp with Kdrive
2. For some reason restart sync from scratch (deleting kdrive config folder)
3. Setup sync again and have available space on comp < Space occupied by files on comp
4. Kdrive will say that it cannot sync because there is not enough space

**Expected behavior**
Kdrive should check which transfers are actually necessary before saying that there is not enough space

**Screenshots**
I freed up some space to get the sync started so i can't reproduce right now.

**Logs**i
is this really needed?

**Additional context**
i think above provided should be enough :)

**Comment by ChristopheLarchier** [comment]
Hello,
Which version are you using?
With version 3.6.0, I don't have this problem.

> Kdrive should check which transfers are actually necessary before saying that there is not enough space
This is what is done.
When you delete the database, the app detects Create-Create pseudo conflicts during the 1st synchronization and calculates the necessary volume as the size on the drive minus the size on the disk.
If you activate the extended trace (Preferences / Debug) before doing the first synchronization, you will see these pseudo conflicts appear in the log.
`2024-05-21 10:29:26:343 [I] (268337669926176) syncpalworker.cpp:195 - *1* ***** Step <Operation Generator> start
2024-05-21 10:29:26:343 [D] (268337669926176) isyncworker.cpp:59 - *1* Worker Operation Generator start
2024-05-21 10:29:26:345 [D] (268337401490720) operationgeneratorworker.cpp:33 - *1* Worker started: name=Operation Generator
2024-05-21 10:29:26:345 [D] (268337401490720) operationgeneratorworker.cpp:159 - *1* Create-Create pseudo conflict detected. Operation Create to be propagated in DB only for item Documents
2024-05-21 10:29:26:345 [D] (268337401490720) operationgeneratorworker.cpp:159 - *1* Create-Create pseudo conflict detected. Operation Create to be propagated in DB only for item test
...`

**Comment by beankylla** [comment]
Hello, 
Was using 3.5.8 
Will update to 3.6.0 and revert back!

**Comment by beankylla** [comment]
different set of issues with 3.6.0 but this one is indeed gone!
