### ISSUE TITLE
Detect and display kDrive in third party file managers

### ISSUE THREAD

**Issue by yaira2** [Infomaniak/desktop-kDrive#182]
*Note: Please write your issue only in english*

**Is your feature request related to a problem? Please describe.**
Hope all is well! We're looking to add support for kDrive in Files (https://files.community) and we wanted to check with you on the best way to do this.

**Describe the solution you'd like to implement**
Ideally, we would verify the installation of kDrive, and upon confirmation, retrieve its path to display in the cloud drives segment of our sidebar

**Additional context**
https://github.com/files-community/Files/issues/15475

![image](https://github.com/Infomaniak/desktop-kDrive/assets/39923744/315eeb6c-ed7c-4022-85a9-008d68f1c2c6)

**Comment by yaira2** [comment]
Thank you! We're looking for the path of the synchronized folders.

**Comment by luc-guyot-infomaniak** [comment]
@yaira2 Did you get all the information you need?
