### ISSUE TITLE
RAM Disk issue

### ISSUE THREAD

**Issue by logusergithub** [Infomaniak/desktop-kDrive#208]
kDrive Desktop 3.61 (and previous versions).

If a RAM disk (R:) is created and the TEMP folder is set on it instead of "%userprofile%\AppData\Local\Temp", kDrive at startup creates the settings folder on the RAM disk instead of "%userprofile%\AppData\Local\kDrive".
To work around the issue I have to set the RAM disk with NTFS instead of exFAT and create a symbolic link at each startup:

if exist "R:\kDrive" RMDIR /S /Q "R:\kDrive"
timeout /t 1
MKLINK /D "R:\kDrive" "C:\Users\%userprofile%\AppData\Local\kDrive"

**Comment by ChristopheLarchier** [comment]
Thanks for the feedback.
This will be corrected in a future version.

**Comment by herve-er** [comment]
@logusergithub, the fix for this issue has been implemented and will be delivered in kDrive version 3.6.3.
