### ISSUE TITLE
Export configuration and folders

### ISSUE THREAD

**Issue by metc** [Infomaniak/desktop-kDrive#259]
**Is your feature request related to a problem? Please describe.**
As a kDrive user, I do have multiple PC/desktop sharing the same folders.
Every time I need to synchronize a new folder, I need to do the same steps manually on each device. Selecting the new kDrive or source folder, selecting the destination folder, the name, etc. I cannot automate this and I have to repeat all the steps manually in the GUI.

**Describe the solution you'd like to implement**
It would be nice to have an option to export and import configurations. The kDrive and folders configurations saved in the local SQLite database. Beeing able to copy a part of the database (export folder configurations to a yml or json files for instance) and reimport this file would ease the process of configuring multiple machines.

**Describe alternatives you've considered**
I would like to have an option to export the configuration at least.
Then, an import function would be nice.
As an alternative, a CLI could be a nice to have so we could add synch folders automatically using scripts.

**Comment by luc-guyot-infomaniak** [comment]
Thanks for your suggestion.
This is indeed a nice a feature to offer to the `desktop-kDrive` users who manage many drives . Coming back to you soon to give you a feel of our time line and how this could fit in our agenda.

**Comment by luc-guyot-infomaniak** [comment]
We cannot follow-up with this issue within a reasonable delay. 

Although such a feature is desirable, and we encourage volunteers to contribute, we have realized that
the implementation and the design are not obvious (a careful choice of data to export needs to be done) 
while it does not belong to our current priority list. 

We keep a detailed record in our backlog though; we will update this issue when needed. 

Thanks for your interest and your suggestion.

**Comment by herve-er** [comment]
Hello,
As this feature is not currently included in our roadmap, we will be closing this issue for now. However, please note that we may reopen it in the future when we will plan to incorporate it into kDrive's development. (As @luc-guyot-infomaniak mentioned, we maintain a record of these suggestions (export and CLI) in the corresponding card within our backlog.)
