### ISSUE TITLE
Unusually high CPU

### ISSUE THREAD

**Issue by jonsnow231** [Infomaniak/desktop-kDrive#28]
**Description**
The CPU is unusually high, turning on my laptop fans. It does this seemingly randomly, and the only way to fix it is to close out of the program and open it back up again. 

**Steps to reproduce**
I don't do anything except let it sync automatically. 

**Logs**
[20240326_2051_kDrive - Copy.log](https://github.com/Infomaniak/desktop-kDrive/files/14805666/20240326_2051_kDrive.-.Copy.log)

**Comment by ClementKunz** [comment]
I do not see anything wrong in your log, just about 250 update of the same file that has been correctly synchronized. Every time a file is modified, a new synchronisation start.
Please, if you notice any reproducible issue, let us now about it.

**Comment by ChristopheLarchier** [comment]
Your Zim editor makes autosaves frequently (by default each time a character is modified in the file or the cursor is moved, see https://zim-wiki.org/) which causes the file synchronization.
You may be able to disable this autosave or otherwise work outside of the sync folder.

**Comment by supertoni3c** [comment]
I experienced the same problem. Regardless if the app is syncing or not the RAM usage is at least 15 GB and the CPU usage is also very high. It happens on Fedora 40 beta with Gnome.
