### ISSUE TITLE
Problem with AppImage

### ISSUE THREAD

**Issue by smiddy** [Infomaniak/desktop-kDrive#38]
**Description**
When I want to integrate the AppImage version with the AppImagelauncher, I get the following error in the terminal:

```
$ ./kDrive-3.5.8.20240227-amd64.AppImage 

(AppImageLauncher:9045): GLib-CRITICAL **: 21:14:31.544: g_file_test: assertion 'filename != NULL' failed

(AppImageLauncher:9045): GLib-CRITICAL **: 21:14:39.160: g_path_get_basename: assertion 'file_name != NULL' failed

** (AppImageLauncher:9045): CRITICAL **: 21:14:39.160: Failed to find desktop file path
```

**Steps to reproduce**
1. Ubuntu 22.04 with AppImagelauncher installer
2. Try to execute the AppImage in the terminal
3. See error

**Expected behavior**
Seamless integration in system.

** Screenshot**
![image](https://github.com/Infomaniak/desktop-kDrive/assets/4051014/b925879d-e323-4914-b29d-07cbf9b10b1b)

**Comment by ClementKunz** [comment]
I checked our AppImage using [appimagelint](https://github.com/TheAssassin/appimagelint) as described [here](https://github.com/TheAssassin/AppImageLauncher/issues/410) and it does not find any blocking issue with it.
For now, I would suggest to run the AppImage without AppImageLauncher or by using the "Run once" button.
If you have any idea on how to solve this issue, please post it here, or submit a PR and we would gladly review it.

**Comment by dunmilli** [comment]
I have the same problem with kDrive-3.6.0.20240521-amd64_b0a75b1ea1feba09158ff886b7c253da.AppImage on Kubuntu 22.04 LTS with AppImagelauncher.
Seems to run OK with "Run once".

**Comment by nicolas-goudry** [comment]
Not really helpful, but I can confirm that this is working on Ubuntu 24.04 (current LTS).

**Comment by luc-guyot-infomaniak** [comment]
@smiddy Is the workaround suggested by @ClementKunz a satisfying solution?
