### ISSUE TITLE
Please, make it more Unix-friendly! Add full Unix LiteSync support

### ISSUE THREAD

**Issue by PEPPEsant01** [Infomaniak/desktop-kDrive#384]
I have used KDrive for some time now. I like it more than other cloud providers because of the superior features related to privacy, and it is generally more polished. Lately though, working from my Linux machine, I came across some limitations; mostly, how synchronization works now is not very practical if you have a lot of files. Although KDrive has rolled out LiteSync to macOS and Windows, the feature is currently not available with Linux, resulting in less efficient file syncing.

Currently, in the absence of LiteSync technology, all cloud files are supposed to sync into the local machine, taking up all the local storage in KDrive-even when such files are not in active use. This is highly problematic, particularly for those with limited disk space, or for users who have to deal with large datasets. LiteSync lets files be downloaded only when needed, hence offering huge advantages on data storage management. Accordingly, it fetches files on-demand and synchronizes incremental changes-the delta-between the cloud and the local machine without having to re-download the whole file from the cloud.

This would definitely enhance the user experience with regards to bandwidth-conserving or disk-space-limited users by having the capability to sync only the delta and retrieve files on-demand. LiteSync, if added to the Linux client, would solve a lot of these issues and would be a huge improvement for users managing large collections of files or working with resource-constrained systems. I believe this would be a big help to Linux users, and I would like to bring it to KDrive's consideration to give priority to developing LiteSync for Linux.

Solution you'd like to implement:
It will be a great help if KDrive can bring this LiteSync functionality to the Linux platform that allows a configuration where files are fetched only upon request and synced in incremental bits, hence reducing consumption on both the local storage and bandwidth. I would also like to see the extension of KDrive support on FreeBSD and other Unix-like systems, such as Illumos-based platforms.

I've been playing around with running FreeBSD from within a virtual machine, and it would be great to get an on-BSD native version of KDrive. Adding support for the BSDs and other *nixes will further make KDrive a bit more flexible and attractive to those using those systems either by choice or due to obligations at work. It will also widen its usage among a wide variety of users who hold the use of Unix-like operating systems in very high regard.

Describe alternatives considered
My interest in LiteSync on Linux and FreeBSD support is strictly because my specific needs regarding usage. I am not pitching KDrive against other cloud services for the time being; rather, I'm simply in need of a more efficient and user-friendly manner of handling cloud synchronization on Linux and FreeBSD. Such changes would mainly increase convenience and performance for me and people in similar situations that either need to use very large data or limited resources.

Additional context
I am migrating from onedrive and google drive to KDrive since a lot of its strong privacy protections and the fact that KDrive's data is stored in Switzerland align with my values regarding data security. I'm looking for a solution that works well on both Linux and FreeBSD systems. Adding LiteSync support to Linux would make a big difference in my workflow. I would also like to be able to use KDrive natively on FreeBSD, because I have now begun experimenting with FreeBSD in a virtual machine, and I would not want to run KDrive but directly on this platform. This will go a long way in managing file synchronization much easier on FreeBSD, thereby being able to enjoy the full power of KDrive.

Thanks for the great job you are doing. I am not in a hurry for these features, but hope they will be taken into consideration and, hopefully, implemented in the near future. Keep it up!

**Comment by ClementKunz** [comment]
Hi @PEPPEsant01 ,
Thank you for your detailed feedback.
LiteSync support on Linux platform is definitively an important feature that is still missing. It is in our plan to provide it some day, but I am unfortunately not able to provide a date for its implementation. We are still focused on increasing stability and reliability.
As for the incremental updates of files, this is a topic that is frequently discussed in the kDrive team and that we would love to implement soon. But since our resources are very limited, it has not been planned yet either.
Hopefully, we will find some time and resources in the near future to make progress on these topics.

Thank you for your confidence
Best,
Clement

**Comment by JorisBodin** [comment]
Hello,

Thank you for your feedback.
The feature requests must be made by our “user-report” of the kDrive project, you have the button for that directly in [kDrive](https://kdrive.infomaniak.com/app/drive/251190). 
<img width="247" alt="image" src="https://github.com/user-attachments/assets/247091e7-8dae-4985-ac50-66d7bad83da2">
